jaffle_shop: # this needs to match the profile in your dbt_project.yml file
    target: dev
    outputs:
        dev:
            type: bigquery
            method: service-account
            keyfile: C:\Users\Minh\jaffle_shop\dbt-user-creds.json # replace this with the full path to your keyfile
            project: valiant-hexagon-353510 # Replace this with your project id
            dataset: dbt_tminh # Replace this with dbt_your_name, e.g. dbt_bilbo
            threads: 1
            timeout_seconds: 300
            location: US
            priority: interactive